stan-dev/stan-dev.github.io

contact/index.md, development/index.md, documentation/index.md, interfaces/index.md, interfaces/shinystan.md
Update names: interface is now ShinyStan and R package is shinystan.
=> shinyStan --> ShinyStan

citations/index.md
I've added the citation for a recently published paper using Stan
=> Add new citation

citations/index.md
=> add 2 dissertations to citations

citations/index.md, documentation/index.md
@syclik Does this look okay? should be a quick sanity check.
=> Update 2.14.0 -> 2.15.0

about/index.md, about/team/index.md
Redirect old team page, and also change the link from "/about/team/index.html" to "/about/team/" on "http://mc-stan.org/about/" (just a small stylistic change).
=> Randommm patch 1

events/stancon2018/index.md, users/documentation/case-studies.md
Just waiting on a few things, but wanted @breckbaldwin to have a chance to review.
I'll merge when when we're ok with it.
=> Updates to StanCon2018 page

_data/developers.yml
Updating from "Stan Group" to "Generable".
=> Updating Daniel's affiliation

users/interfaces/cmdstan.md
I noticed that the link is broken, but since it is a small bug, I will respond with PR instead of an issue.
=> fixed broken link

events/stancon2018Helsinki/index.md
Removed link to my (dated) linkedin page
=> Small edit

about/index.md, about/sgb/minutes.md
@breckbaldwin, can you take a look?
=> SGB: Adding 9/26 minutes

about/index.md, about/sgb/minutes.md
I've also fixed line endings and line lengths in the minutes.
@breckbaldwin, I took a little liberty in taking out info on who did the talking. Let me know if that's ok.
=> Adding SGB minutes from 10/03

misc/warnings.Rmd
=> typo in Warnings.Rmd

about/index.md, about/sgb/minutes.md
=> sgb minutes: 9/26/2019

about/index.md, about/sgb/minutes.md
Adding SGB minutes for the 10/17/2019 meeting.
=> adding SGB 10/17/2019 minutes

about/index.md
Updating SGB page so it reflects Breck's departure from SGB.
=> removing Breck from SGB

_data/navigation.yml, _includes/head.html, _includes/navigation.html, _includes/scripts.html, _sass/_navigation.scss, _sass/_reset.scss, _sass/_variables.scss, assets/js/nav.js, search/search.md
I definitely appreciate the addition of the search feature on the website, but I think the original creator of the [So Simple](https://github.com/mmistakes/so-simple-theme) theme had the right idea of including it on it's own page. I've also implemented the original responsive features of So Simple so that the site renders properly on all devices.
=> Adjusting Aesthetics

about/index.md, about/sgb/minutes.md
Posting SGB minutes for 10/14/2019.
=> SBG minutes for 10/14/2019

events/stancon2020/index.md
Add Susana & Eric to the list of StanCon 2020 organizers.
=> Add Susana & Eric to organizers

events/stancon2020/index.md
Adding updated announcement information for StanCon.
=> adding updated information for StanCon 2020

events/stancon2020/index.md
Add `<>` around links to make them active.
=> Fix stancon2020 links

users/documentation/case-studies/reduce_sum_tutorial.html
This is the html component of: https://github.com/stan-dev/example-models/pull/176
=> Updated reduce_sum tutorial for cmdstanr threading interface change (example-models issue #175)

users/documentation/case-studies/reduce_sum_tutorial.html
Switched the reduce_sum tutorial to use cores/chains instead of num_cores/num_chains.
=> Updated num_cores/num_chains to chains/cores

_config.yml
Updating the logo for pride month.
=> Pride month

users/documentation/case-studies/reduce_sum_tutorial.html
This updates the reduce_sum tutorial to track the changes to threading/cores/chains in cmdstanr: https://github.com/stan-dev/cmdstanr/pull/185
=> Updated reduce_sum tutorial for latest cmdstanr changes

users/documentation/case-studies/convert_odes.html
This is a bug fix.
Updating links in convert_odes example
=> Updated links to models in convert_odes case study (design-doc #19)

users/documentation/index.md, users/interfaces/cmdstan.md
=> Docs updated by Jenkins for v2-24

about/logo/index.md
Was digging around the site and came across this broken link.
=> fixing numFOCUS and SGB links

.travis.yml, users/documentation/index.md, users/interfaces/cmdstan.md
This is a documentation change.
Updating site references to docs version 2.25
https://github.com/stan-dev/math/issues/2128
=> Documentation generated for docs-2-25

events/stancon2020/index.md
Tagging @syclik as a potential reviewer.
=> Add notebook link for Charles et al's talk.

users/documentation/case-studies/reduce_sum_tutorial.html
This updates the reduce sum tutorial .html
=> Updated reduce sum tutorial with lupdf information

users/documentation/index.md, users/interfaces/cmdstan.md
=> Docs updated by Jenkins for v2-26

users/documentation/case-studies.md
The case study now has a more in-depth example of covid-19 transmission in Switzerland.
=> updated the disease transmission case study and changed the source repo

about/index.md
Just provide 2021 SGB names & link to discourse general updates.
=> SGB 2021 & links

users/documentation/index.md.bak, users/interfaces/cmdstan.md.bak
=> Docs updated by Jenkins for v2-27

.gitignore, _config.yml
=> Rainbow 2021

users/documentation/index.md, users/documentation/index.md.bak, users/interfaces/cmdstan.md, users/interfaces/cmdstan.md.bak
=> Docs updated by Jenkins for v2-28

about/index.md
=> Fix Jose Storopoli's affiliation at SGB

users/documentation/index.md, users/documentation/index.md.bak, users/interfaces/cmdstan.md, users/interfaces/cmdstan.md.bak
=> Docs updated by Jenkins for v2-29

users/documentation/index.md, users/documentation/index.md.bak, users/interfaces/cmdstan.md, users/interfaces/cmdstan.md.bak
Docs updated through the [Jenkins Job](https://jenkins.flatironinstitute.org/job/Stan/job/BuildDocs/)
=> Docs updated by Jenkins for v2-31

_data/developers.yml
=> Update Andre's contact info

users/documentation/index.md, users/interfaces/cmdstan.md
Update docs version from 2.31 to 2.32
=> Documentation generated for docs-2-32

about/logo/index.md
I made some suggestions that would address the issue raised at [discourse](https://discourse.mc-stan.org/t/trademark-protection-for-stan-name-and-logo/28629/)
=> Update instructions about our logo

users/documentation/index.md, users/interfaces/cmdstan.md
Docs updated through the [Jenkins Job](https://jenkins.flatironinstitute.org/job/Stan/job/BuildDocs/)
=> Docs updated by Jenkins for v2-33

index.md
Add pathfinder to the algorithms mentioned on the home page.
=> mention pathfinder on homepage along with advi

users/interfaces/cmdstan.md
Docs updated through the [Jenkins Job](https://jenkins.flatironinstitute.org/job/Stan/job/BuildDocs/)
=> Docs updated by Jenkins for v2-35

users/interfaces/cmdstan.md
Docs updated through the [Jenkins Job](https://jenkins.flatironinstitute.org/job/Stan/job/BuildDocs/)
=> Docs updated by Jenkins for v2-36

index.qmd
Mostly based on feedback from @bob-carpenter 
Here's a preview:
=> Alt. homepage formatting

tools/index.qmd
General formatting and listing a few newcomers
=> Updates to the tools page on syntax highlighters
